import mitt from "mitt";
export const mitter = mitt();
export const EVENT = {
	WORKFLOW_EVENT: "WORKFLOW_EVENT",
	PANEL_SHOW_ADD_WORKFLOW:"PANEL_SHOW_ADD_WORKFLOW",
	PANEL_SHOW_ADD_STEP:"PANEL_SHOW_ADD_WORKFLOW",
	FIRE_MAN_ARRIVED:"FIRE_MAN_ARRIVED",
	FIRE_WALL_CREATED:"FIRE_WALL_CREATED",
};
